export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       Contact page mai apka swagat hai {children}
      </body>
    </html>
  );
}
